FROM python:3-slim
WORKDIR /usr/src/app
COPY requirements.txt ./
EXPOSE 5000
RUN python -m pip install --no-cache-dir -r requirements.txt
COPY ./websocket-client.py ./
CMD [ "python", "./websocket-client.py" ]